---
title: "Determining exponential function"
output: html_notebook
---

The relationship between months to pay back and monthly payment appears to be exponential. I want to see if I can approximate this, partially for speed ups and partially to be able to evaluate what makes certain loans benefit more from overpayment.

First let's get the data:

```{r}
library(lubridate)
library(tidyverse)

source("loans_calc/source.R")
```


```{r}
x <- list(salliemae = list(name = "Commonbond", balance = 14224.17, int = 0.0445,
                           min_pay = 275.54, fixed = F, months_left = NA),
          navient1 = list(name = "Navient 1", balance = 2465.31, int = 0.0535,
                          min_pay = 38.04, fixed = T, months_left = 85),
          navient2 = list(name = "Navient 2", balance = 3786.76, int = 0.0315,
                          min_pay = 54.32, fixed = T, months_left = 85),
          navient3 = list(name = "Navient 3", balance = 1199.6, int = 0.0655,
                          min_pay = 31.09, fixed = T, months_left = 85),
          navient4 = list(name = "Navient 4", balance = 3999.17, int = 0.0655,
                          min_pay = 95.80, fixed = T, months_left = 85))

payoff_options <- get_payoff_options(x)

payoff_options

plot_payoff_options(payoff_options)

```


