---
title: "Loan Repayment"
output: html_notebook
---

```{r}
source("source.R")
```


```{r}
library(tidyverse)
library(lubridate)

x <- list(list(name = "Commonbond", balance = 12916.83, int = 0.0445, min_pay = 275.54),
          list(name = "Navient 1", balance = 2243.34, int = 0.0535, min_pay = 38.04),
          list(name = "Navient 2", balance = 3426.51, int = 0.0315, min_pay = 54.32),
          list(name = "Navient 3", balance = 933.43, int = 0.0655, min_pay = 31.09),
          list(name = "Navient 4", balance = 3217.86, int = 0.0655, min_pay = 95.80))

x <- list(list(name = "Commonbond", balance = 12916.83, int = 4.45, min_pay = 275.54),
          list(name = "Navient 1", balance = 2243.34, int = 5.35, min_pay = 38.04),
          list(name = "Navient 2", balance = 3426.51, int = 3.15, min_pay = 54.32),
          list(name = "Navient 3", balance = 933.43, int = 6.55, min_pay = 31.09),
          list(name = "Navient 4", balance = 3217.86, int = 6.55, min_pay = 95.80))

```

```{r}

```

```{r, fig.height= 6, fig.width = 3}

opt <- get_payoff_options(x)

vals <- payoff_options$mo_pay
vals_use <- c(vals[1:2], vals[which(vals %% 100 == 0)])
vals_use <- vals_use[!duplicated(vals_use)]

factor_levels <- c()
payment_sched <- purrr::map_df(vals_use, function(mo_pay){
  print(mo_pay)
  lab <- ifelse(is.na(mo_pay), "Minimum", sprintf("$%0.2f", mo_pay))
  factor_levels <<- c(factor_levels, lab)
  
  conduct_schedule_analysis(x, max_mo_pay = mo_pay) %>%
    mutate(mo_pay = lab)
}) 

payment_sched$mo_pay <- factor(payment_sched$mo_pay, levels = factor_levels)

cols = c("#11CEC4", "#218ED2", "#3250D6", "#6A43DA", 
         "#B455DE", "#E267D2", "#E67AA9", "#EB8EBE")

cols_use_seq = seq(1, 8, by = floor(8/length(unique(payment_sched$name))))

cols_use = cols[cols_use_seq]

max_y <- baremin_gather %>% 
  filter(group == "Total interest to be paid") %>%
  mutate(max_y = value + padding) %>%
  pull(max_y)

if(max_y > 3000){ breaks <- seq(0, max_y, by = 500)
} else breaks <- seq(0, max_y, by = 200)

p1 <- ggplot(payment_sched, aes(x = month, y = payment)) +
  facet_wrap(~ mo_pay, ncol = 1) +
  geom_bar(stat = "identity", color = "white", aes(fill = name), alpha = .6, size = .1) +
  labs(title = "Payments over time", y = "Monthly Payment", color = "") +
  scale_fill_manual("", values = cols_use) +
  scale_x_continuous("Month from now", breaks = seq(12, max(payment_sched$month), by = 12)) +
  ggthemes::scale_color_gdocs() +
  #scale_color_manual("", values = "red") +
  theme_linedraw() +
  scale_y_continuous(labels = scales::dollar_format(prefix="$")) +
  guides(fill=FALSE) +
  theme(
    axis.title.y=element_blank(),
    axis.text.y = element_text(size = 6),
    strip.background = element_blank(),
    strip.text.x = element_blank()
  )

p2 <- ggplot(payment_sched, aes(x = month, y = new_balance)) +
  facet_wrap(~ mo_pay, ncol = 1) +
  geom_bar(stat = "identity", color = "white", aes(fill = name), alpha = .6, size = .1) +
  labs(title = "Balance over time", y = "Remaining Balance", color = "") +
  scale_fill_manual("", values = cols_use) +
  scale_x_continuous("Month from now", breaks = seq(12, max(payment_sched$month), by = 12)) +
  ggthemes::scale_color_gdocs() +
  #scale_color_manual("", values = "red") +
  theme_linedraw() +
  scale_y_continuous(labels = scales::dollar_format(prefix="$")) +
  guides(fill=FALSE) +
  theme(
    axis.title.y=element_blank(),
    axis.text.y = element_text(size = 6),
    strip.background = element_blank(),
    strip.text.x = element_blank()
  )

factor_levels <- c()

empty_dat <- purrr::map_df(vals_use, function(mo_pay){
  lab <- ifelse(is.na(mo_pay), "Minimum\npayments", sprintf("$%0.2f/mo", mo_pay))
  factor_levels <<- c(factor_levels, lab)
  
  data.frame(x = 0, y = 0, mo_pay = lab, stringsAsFactors = F)
})

empty_dat$mo_pay <- factor(empty_dat$mo_pay, levels = factor_levels)

p0 <- ggplot(empty_dat, aes(x = x, y = y)) +
  geom_blank() +
  facet_wrap(~mo_pay, ncol = 1) +
   theme(
      strip.background = element_blank(),
      strip.text.x = element_blank(),
      axis.text.x=element_blank(),
      axis.ticks.x=element_blank(),
      axis.text.y=element_blank(),
      axis.ticks.y=element_blank(),
      panel.grid.major = element_blank(), 
      panel.grid.minor = element_blank(),
      panel.background = element_blank()
    ) +
  labs(x = "", y = "") +
  geom_text(aes(label = mo_pay), size = 4)

gridExtra::grid.arrange(p0, p1, p2, ncol = 3, widths = c(4,8,8))

```


Still broken for when two loans get paid off in same month! Doesn't apply second overpayment...
Happens for 4 loans, 398.99/mo

Try out:

```{r}
x4 <- x[1:4]

sched <- conduct_schedule_analysis(x[1], max_mo_pay = NA, int_tiebreak = "higher balance")

opt <- get_all_schedules(x[1:4])

plot_opt <- opt %>%
      group_by(mo_pay) %>%
      summarize(`Months to pay off` = max(month),
                `Total interest to be paid` = sum(int_pay)) %>%
      mutate(mo_pay = mo_pay) %>%  
      arrange(!is.na(mo_pay), mo_pay)

plot_payoff_options_v2(plot_opt)
```

```{r}
st <- list(list(name = "loan 1", balance = 5000, int = 4.5, min_pay = 93.22),
           list(name = "loan 2", balance = 8000, int = 3.5, min_pay = 145.53))

opt <- get_all_schedules(st)


plot_opt <- opt %>%
      group_by(mo_pay) %>%
      summarize(`Months to pay off` = max(month),
                `Total interest to be paid` = sum(int_pay)) %>%
      mutate(mo_pay = mo_pay) %>%  
      arrange(!is.na(mo_pay), mo_pay)

opt %>%
  filter(mo_pay %in% unique(opt$mo_pay)[1:2]) %>%
  group_by(mo_pay) %>%
  summarize(max_mo = max(month)) %>%
  pull(max_mo) %>%
  unique() %>%
  length()


```



